config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "products#index"

  post "spgateway/return"
  post "spgateway/notify"


  resources :products, only: [:index, :show] do 
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    
    get :about, on: :collection
  end
  
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :products, only: [:index, :show]
    end
  end

  resource :cart   #當你設定單數資源時，網址的表達會變成 /cart 而不是 /cart/:id，就會直接對應到 show action

  resources :orders do
    post :checkout_spgateway, on: :member
  end

  namespace :admin do
    resources :products
    resources :orders
    resources :users
    root "products#index"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
  has_many :payments

  #必填
  validates_presence_of :name, :address, :phone, :amount
  validates :phone, length: { in: 8..14 }
  validates :payment_status, inclusion: { in: %w(not_paid paid), message: "%{value} is not a valid PAYMENT_STATUS" }
  validates :shipping_status, inclusion: { in: %w(not_shipped shipped cancelled), message: "%{value} is not a valid SHIPPING_STATUS" }

  # set constant to generate select options
  PAYMENT_STATUS = [
    ["Not Paid", :not_paid],
    ["Paid", :paid]
  ]

  SHIPPING_STATUS = [
    ["Not Shipped", :not_shipped],
    ["Shipped",:shipped],
    ["Cancelled",:cancelled]
  ]
  
  def add_order_items(cart)
    cart.cart_items.each do |item|
      self.order_items.build(
        product_id: item.product.id,
        quantity: item.quantity,
        price: item.product.price
        )
    end
  end

  def subtotal
    order_items.map{ |x| x.item_total }.sum
  end

  def count_sold
    if payment_status == "paid"
      order_items.each do |item|
        product = Product.find(item.product_id)
        product.sold_count += item.quantity
        product.save
      end
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @q = Order.includes(:user).order("id DESC").ransack(params[:q])
    @orders = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def edit
    @order = Order.includes(:order_items, order_items: :product).find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "order was successfully updated"
      if @order.shipping_status == "shipped"
        #UserMailer.notify_order_shipped(@order).deliver_now
      end

      @order.count_sold
        #UserMailer.notify_order_paid(@order).deliver_now
      redirect_to admin_orders_path(@order)
    else
      flash.now[:alert] = @order.errors.full_messages.to_sentence
      render "admin/orders/edit"
    end
  end


  private

  def order_params
    params.require(:order).permit(:shipping_status, :payment_status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.includes(:user, :products).where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(3)
  end

  def create
    # manually check if user logged in
    if current_user.nil?
      # store order data in session so we can retrieve it later
      session[:new_order_data] = params[:order]
      # redirect to devise login page
      redirect_to new_user_session_path
    elsif current_cart.subtotal != 0
      @order = current_user.orders.new(order_params)
      @order.sn = Time.now.to_i+current_user.id
      @order.add_order_items(current_cart)
      @order.amount = current_cart.subtotal
      if @order.save
        current_cart.destroy
        session.delete(:new_order_data)
        #UserMailer.notify_order_create(@order).deliver_now!
        redirect_to orders_path, notice: "new order created"
      else
        @items = current_cart.cart_items
        render "carts/show"
      end
    else
      flash[:alert] = "Cart created failed."
      redirect_to root_path
    end
  end

  def update
    @order = current_user.orders.find(params[:id])
    if @order.shipping_status == "not_shipped"
      @order.shipping_status = "cancelled"
      @order.save
      redirect_to orders_path, alert: "order##{@order.sn} cancelled."
    end
  end

  def checkout_spgateway
    @order = current_user.orders.find(params[:id])
    if @order.payment_status != "not_paid"
      flash[:alert] = "Order has been paid."
      redirect_to orders_path
    else
      @payment = Payment.create(
        sn: Time.now.to_i,
        order_id: @order.id,
        payment_method: params[:payment_method],
        amount: @order.amount
        )

      render layout: false
      #將 layouts/application.html.erb 關掉，也就是不需要 Navbar，目的是讓畫面愈快愈好
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :phone, :address, :payment_method)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def can_pay?(order)
    order.payment_status == "not_paid" && order.shipping_status != "cancelled"
  end

#訂單未付款
  def not_shipped?(order)
    order.shipping_status == "not_shipped"
  end

end

app/views/admin/orders/edit.html.erb
<div class="container">
  <div class="row">
    <div class= "order-content clearfix">
      <%= form_for [:admin, @order] do |f| %>
        <h3>Order#<%= @order.id %></h3>
        <div class="order-detail">
          <%= render partial: "shared/order-detail" , locals: { order: @order } %>
        </div>

        <div class="order-status">
          <div class="col-md-6">
            <p>Payment Status: <%= f.select :payment_status, Order::PAYMENT_STATUS %></p>
            <p>Shipping Status: <%= f.select :shipping_status, Order::SHIPPING_STATUS %></p>
            <%= f.submit %>
          </div>
        </div>
      <% end %>
    </div>    
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <h3>後台</h3>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to 'Products', admin_products_path, class: "btn btn-default" %>
        <%= link_to 'Orders', admin_orders_path, class: "btn btn-primary" %> 
        <%= link_to 'Users', admin_users_path, class: "btn btn-default" %>
      </div>
      <div>
        <h5>
          <span>*Paid Order: <%= Order.where(payment_status: "paid").size %></span>
          <span>*Shipped Order: <%= Order.where(shipping_status: "shipped").size %></span>
          <span>*Order Count: <%= Order.find_each.size %></span>
        </h5>
      </div>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th><%= sort_link(@q, :id, 'Id', default_order: :asc) %></th>
            <th><%= sort_link(@q, :sn, 'Order Number', default_order: :asc) %></th>
            <th><%= sort_link(@q, :user_email, 'Customer', default_order: :asc) %></th>
            <th><%= sort_link(@q, :amount, 'Amount', default_order: :asc) %></th>
            <th><%= sort_link(@q, :payment_status, 'Payment status', default_order: :asc) %></th>
            <th><%= sort_link(@q, :shipping_status, 'Shipping status', default_order: :asc) %></th>
            <th>Order Detail</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= order.id %></td>
            <td><%= order.sn %></td>
            <td><%= order.user.email %></td>
            <td><%= order.amount %></td>
            <td><%= order.payment_status %></td>
            <td><%= order.shipping_status %></td>
            <td>
              <%= link_to edit_admin_order_path(order) do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
       <div class="text-center">
        <%= paginate @orders %>
      </div>
     </div>
   </div>
</div>