config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "products#index"

  post "spgateway/return"
  post "spgateway/notify"


  resources :products, only: [:index, :show] do 
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    
    get :about, on: :collection
  end
  
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :products, only: [:index, :show]
    end
  end

  resource :cart   #當你設定單數資源時，網址的表達會變成 /cart 而不是 /cart/:id，就會直接對應到 show action

  resources :orders do
    post :checkout_spgateway, on: :member
  end

  namespace :admin do
    resources :products
    resources :orders
    resources :users
    root "products#index"
  end
end

app/views/shared/_cart.html.erb
<section id="my-cart">
  <div class ="item-list">
      <!------collection取代.each do |item|...end----------->
      <%= render partial: "shared/item", collection: current_cart.cart_items %>
  </div>
  <hr>
  <div class="under-my-cart">
    <div class="subtotal">
      <p><%= t(:subtotal) %></p>
      <p class="amount">$ <%= current_cart.subtotal %></p>
    </div>
  
    <div class="button" id="cart-button">   
      <%= render partial: "shared/cart_button" %>
    </div>
  </div>
  
</section>

app/views/shared/_cart_button.html.erb
<% if cart_has_things? %>
  <%= link_to cart_path(current_cart), class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
  <% end %>
<% end %>

<% if !!current_user %>
  <%= link_to orders_path(current_user.orders), class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
  <% end %>
<% end %>

app/views/shared/_item.html.erb
<div class="cart-item product-<%= item.product.id %> clearfix">
  <div class="col-sm-6 col-md-4">
    <%= show_product_picture item.product %>
  </div>

  <div class="col-sm-6 col-md-8">
    <p><%= item.product.name %></p>
    <p>$ <%= item.product.price %></p>
    <div class="cart-item-adjust">
      <%= link_to '+', adjust_item_product_path(item.product, type: "add"), method: :post, remote: true %>
      <span class="cart-<%= item.product.id %>-qty"><%= item.quantity %></span>  
      <%= link_to '-', adjust_item_product_path(item.product, type: "substract"), method: :post, remote: true %>
      <!----ink_to 不可以省略method: :post ，button_to可以----->  
      <%= button_to remove_from_cart_product_path(item.product), remote: true, class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_order-detail.html.erb
<div class="col-md-6">
  <div class="orderitems-list">
    <table class="table table-striped">       
      <tbody>
        <% order.order_items.each do |item| %>
        <tr>
          <td><%= item.product.name %></td>
          <td><%= item.quantity %></td>
          <td>$ <%= item.price %></td>
        </tr>
          
        <% end %>
      </tbody>               
      <tbody> 
        <tr>
          <th><p>Subtotal</p></th>
          <th></th>
          <th>$ <%= order.amount %></th>                       
        </tr>                                                              
      </tbody>
    </table>
  </div>
<!--------->
  <div class="shipping_info">
    <ul class="list-group list-group-flush">
      <li class="list-group-item list-group-item-info">Shipping Information</li>
      <li class="list-group-item">Name: <%= order.name %></li>
      <li class="list-group-item">Phone: <%= order.phone %></li>
      <li class="list-group-item">Address: <%= order.address %></li>
    </ul>                
  </div>
</div>

app/views/shared/_order_item.erb
<div class="panel panel-order clearfix">
    <%= form_for [:admin, order] do |f| %>
        <h3>Order#<%= order.sn %></h3>
        <div class="order-detail">
            <div class="col-md-6">
                <div class="orderitems-list">
                    <table class="table table-striped">       
                    <tbody>
                        <% order.order_items.each do |item| %>
                        <tr>
                        <td><%= item.product.name %></td>
                        <td><%= item.quantity %></td>
                        <td>$ <%= item.price %></td>
                        </tr>
                        
                        <% end %>
                    </tbody>               
                    <tbody> 
                        <tr>
                        <th><p>Subtotal</p></th>
                        <th></th>
                        <th>$ <%= order.amount %></th>                       
                        </tr>                                                              
                    </tbody>
                    </table>
                </div>
                <!--------->
                <div class="shipping_info">
                    <ul class="list-group list-group-flush">
                    <li class="list-group-item list-group-item-info">Shipping Information</li>
                    <li class="list-group-item">Name: <%= order.name %></li>
                    <li class="list-group-item">Phone: <%= order.phone %></li>
                    <li class="list-group-item">Address: <%= order.address %></li>
                    </ul>                
                </div>
            </div>
        </div> 

        <div class="order-status">
            <div class="col-md-6">
                <p>Payment Status: <%= order.payment_status %></p>
                <p>Shipping Status: <%= order.shipping_status %></p>
                <% if can_pay?(order) %>
                    <% Payment::PAYMENT_METHODS.each do |method| %>
                        <%= link_to method, checkout_spgateway_order_path(order, payment_method: method), method: :post, class: "btn btn-primary" %>
                    <% end %>
                <% end %>

                <% if not_shipped?(order) %>
                    <%= link_to "Cancer Order", order_path(order), method: :patch, class: "btn btn-default", data: { confirm: "Are you sure?"} %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>  

app/views/shared/_products.html.erb
<div class="hidden-xs">
  <div class="col-sm-12 col-md-4 col-lg-3">
    <div class="product-box product_<%= product.id %>">
      <%= link_to product_path(product) do %>
        <%= show_product_picture product %>
      <% end %>

      <div class="caption">
        <h4><%= link_to product.name, product_path(product) %></h4>
        <p><%= truncate(product.description, length: 17) %></p>
        <p>$ <%= product.price %><p>
          <div class="add-to-cart">
            <%= button_to add_to_cart_product_path(product), remote: true, class: "btn btn-default" do %>
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>