config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "products#index"

  post "spgateway/return"
  post "spgateway/notify"


  resources :products, only: [:index, :show] do 
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    
    get :about, on: :collection
  end
  
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :products, only: [:index, :show]
    end
  end

  resource :cart   #當你設定單數資源時，網址的表達會變成 /cart 而不是 /cart/:id，就會直接對應到 show action

  resources :orders do
    post :checkout_spgateway, on: :member
  end

  namespace :admin do
    resources :products
    resources :orders
    resources :users
    root "products#index"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :price #必填
  validates :name, uniqueness: true
  validates_numericality_of :price, greater_than_or_equal_to: 1
  mount_uploader :image, PhotoUploader #圖片上傳器

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:edit, :update]
  
  def index
    @q = Product.order("id DESC").ransack(params[:q])
    @products = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def new 
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "product was successfully created"
      redirect_to admin_products_path
    else
      flash.now[:alert] = "product was failed to create"
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = "product was successfully updated"
      redirect_to admin_products_path(@product)
    else
      flash.now[:alert] = "product was failed to update"
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :image, :description, :price, :on_sold)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApiController
  before_action :authenticate_user!, except: :index
  def index 
    @products = Product.find_each
  end

  def show
    @product = Product.find_by(id: params[:id])
    if !@product
      render json: {
        message: "Can't find the product!",
        status: 400
      }
    else
      render "api/v1/products/show"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :add_to_cart, :remove_from_cart, :adjust_item]
  
  def index
    @search = Product.where(on_sold: true)
    if params[:name] 
      @search = @search.where("name LIKE ?", "%#{params[:name]}%")
    end
    @products = @search.page(params[:page]).per(12)
    @items = current_cart.cart_items
  end

  def show
    @items = current_cart.cart_items
  end

  def add_to_cart   
    current_cart.add_cart_item(@product)

    #redirect_back(fallback_location: root_path)
  end

  def remove_from_cart
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    cart_item.destroy
    #redirect_back(fallback_location: root_path)
  end

  def adjust_item
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    if params[:type] == "add"
      cart_item.quantity += 1
    elsif params[:type] == "substract"
      cart_item.quantity -= 1
    end

    if cart_item.quantity == 0
      cart_item.destroy
    else
      cart_item.save
    end

    #redirect_back(fallback_location: root_path)
  end

  #rspec
  def about
    @user_count = User.get_user_count
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
#顯示商品照片
  def show_product_picture(product)
    if product.image?
      image_tag product.image.url, class: "img-responsive center-block"
    else
      content_tag :span, class: "glyphicon glyphicon-picture"
    end
  end
end

app/views/admin/products/_form.html.erb
<div class="container">
  <div class="row">
    <% if @product.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %>

  <%= form_for [:admin, @product] do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "On Sold" %>
      <%= f.check_box :on_sold %>
    </div>

    <div class="form-group">
      <%= f.label :image, "Photo" %>
      <%= image_tag @product.image.url, width: '300px' if @product.image? %>
      <%= f.file_field :image %>
    </div>     

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :price, "Price" %>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/products/_products.html.erb
<tr>
  <th scope="row"><%= product.id %></th>
  <td>
  <% if product.on_sold == false %>
    <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
  <% end %>
  <%= product.name %>
  </td>
  <td><%= product.price %></td>
  <td><%= product.sold_count %></td>
  <td>
    <%= link_to edit_admin_product_path(product) do %>
      <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
    <% end %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<%= render partial: "form" %>

app/views/admin/products/index.html.erb
<div class="container">
  <h3>後台</h3>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to 'Products', admin_products_path, class: "btn btn-primary" %>
        <%= link_to 'Orders', admin_orders_path, class: "btn btn-default" %> 
        <%= link_to 'Users', admin_users_path, class: "btn btn-default" %>
      </div>
      </br>
      <div>
        <%= link_to 'New Product', new_admin_product_path, class: "btn btn-primary" %>

        <%= search_form_for @q, url: admin_products_path do |f| %>
          <%= f.label  :name_cont %>
          <%= f.search_field :name_cont %>
          <%= f.submit %>
          
        <% end %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr class="order-link">
            <th><%= sort_link(@q, :id, 'Id', default_order: :asc) %></th>
            <th><%= sort_link(@q, :name, 'Name', default_order: :asc) %></th>
            <th><%= sort_link(@q, :price, 'Price', default_order: :asc) %></th>
            <th><%= sort_link(@q, :sold_count, 'Sold Amount', default_order: :asc) %></th>
            <th>#</th>
          </tr>
        </thead>
        <tbody id="products">
          <%= render partial: "products", collection: @products, as: :product %>
        </tbody>
      </table>
      <div class="text-center">
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% if @product.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @product] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :image, "Image" %>
  <%= f.file_field :image %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.label :price, "Price" %>
  <%= f.text_field :price %>
  

  <%= f.submit %>
<% end %>