config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "products#index"

  post "spgateway/return"
  post "spgateway/notify"


  resources :products, only: [:index, :show] do 
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
    
    get :about, on: :collection
  end
  
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :products, only: [:index, :show]
    end
  end

  resource :cart   #當你設定單數資源時，網址的表達會變成 /cart 而不是 /cart/:id，就會直接對應到 show action

  resources :orders do
    post :checkout_spgateway, on: :member
  end

  namespace :admin do
    resources :products
    resources :orders
    resources :users
    root "products#index"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :orders, dependent: :destroy

  scope :admin, -> { where("role = ?", 'admin') }

  before_create :generate_authentication_token
  #before_destroy :ckeck_admin_enough
  before_update :ckeck_admin_enough

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

  def admin?
    self.role == "admin"
  end

#facebook or google傳入的登入資料
  def self.from_omniauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    if user 
      return user
    else
      existing_user = User.where(email: auth.info["email"]).first
      if existing_user
        return existing_user
      else
        user = User.create(
          email: auth.info.email,
          password: Devise.friendly_token[0,20],
          name: auth.info.name,
          avatar: auth.info.image 
        )
      end
    end
  end

  #rspec
  def self.get_user_count
    User.all.size
  end

  def ckeck_admin_enough
    unless admin_enough?
      errors[:base] << "admin not enough!!!"
      throw :abort      #中斷回呼
    end
  end

  def admin_enough?
    User.admin.size > 1 || admin? == false
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:edit, :update, :destroy]
  
  def index
    @q = User.order("role DESC").order("id DESC").ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "user was successfully updated"
      redirect_to admin_users_path()
    else
      flash.now[:alert] = "user was failed to update"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:alert] = "user was deleted"
    else
      flash[:alert] = @user.errors[:base]
    end
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:avatar, :name, :email, :role)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}") if is_navigational_format?
    #缺資料時導回註冊頁面
    else
      session["devise.#{provider}data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, alert: "無法獲得驗證！"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
    <h2>We have some errors here !</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for [:admin, @user] do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :avatar, "Avatar" %><br/>
      <%= image_tag @user.avatar.url, width: '300px' if @user.avatar? %>
      <%= f.file_field :avatar %>
    </div>

    <div class="form-group">
      <%= f.label :role, "Role" %>
      <%= f.text_field :role, class: "form-control" %>
    </div>

    <%= f.submit "Comfirm", class: "btn btn-primary" %>
    
  <% end %>
  <br>

  <%= link_to 'Cancel', admin_users_path, class: "btn btn-default" %>

</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h3>後台</h3>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to 'Products', admin_products_path, class: "btn btn-default" %>
        <%= link_to 'Orders', admin_orders_path, class: "btn btn-default" %> 
        <%= link_to 'Users', admin_users_path, class: "btn btn-primary" %>
      </div>
      <br>

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th><%= sort_link(@q, :id, 'Id', default_order: :asc) %></th>
            <th><%= sort_link(@q, :name, 'Name', default_order: :asc) %></th>
            <th><%= sort_link(@q, :email, 'Email', default_order: :asc) %></th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td>
              <span class="badge"><%= user.role %></span>
              <%= user.name %>
            </td>
            <td><%= user.email %></td>
            <td>
              <%= link_to edit_admin_user_path(user) do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
              <% end %>
              
              <%= link_to admin_user_path(user), method: :delete, data: { confirm: "Are you sure?"} do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-center">
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>